const systemScanLogs = [
    "Scanning network topology... completed.",
    "Detected firewall protocols: ZoneAlarm, IPTables, FortiGate",
    "Initiating port scan on VenturoCorp main server...",
    "Port 22 (SSH) - Open",
    "Port 80 (HTTP) - Open",
    "Port 443 (HTTPS) - Open",
    "Port 8080 (HTTP Proxy) - Open",
    "Port 3306 (MySQL) - Open",
    "Suspicious port 1337 - Open (Unknown Service)",
    "Port 3389 (Remote Desktop) - Closed",
    "IP Address range detected: 192.168.0.1 - 192.168.255.255",
    "Analyzing open ports for vulnerabilities...",
    "Vulnerability detected: CVE-2023-4001 - SSH overflow",
    "Scanning for active services...",
    "Service detected: Apache/2.4.46 (Ubuntu)",
    "Service detected: MySQL 8.0.22",
    "Service detected: Nginx 1.18.0",
    "Service detected: Jenkins Continuous Integration",
    "Suspicious activity: Unusual traffic on Port 9999",
    "Analyzing SSL certificates...",
    "Expired SSL certificate found: *.venturocorp.com (expired 200 days ago)",
    "Weak encryption protocol detected: TLSv1.0",
    "Conducting DNS lookup...",
    "DNS resolved for venturocorp.com - 104.31.78.219",
    "Analyzing DNS records...",
    "Subdomain detected: dev.venturocorp.com",
    "Subdomain detected: payments.venturocorp.com",
    "Subdomain detected: intranet.venturocorp.com",
    "Suspicious subdomain detected: root-access.venturocorp.com",
    "Checking for default credentials...",
    "Default password 'admin123' found for Jenkins server",
    "Password hash discovered: $argon2id$v=19$m=4096,t=3,p=1$N2e1bXgk$cyIxdm...",
    "Exposed database found on Port 27017 (MongoDB)",
    "Checking for exposed S3 buckets...",
    "S3 bucket 'venturocorp-secrets' found - Public access enabled",
    "Running SQL injection test on venturocorp.com/login...",
    "Potential SQL injection vulnerability detected",
    "Database schema discovered: venturo_users, venturo_payments",
    "User table found with 105,000 records",
    "Weak password hashing algorithm: MD5",
    "Admin credentials detected in plaintext: admin@venturocorp.com",
    "Sensitive file found: /etc/venturocorp/config.json",
    "Scanning for system logs...",
    "Log file found: /var/log/venturo/errors.log",
    "Security breach logs: 15 unauthorized attempts in last 24 hours",
    "Suspicious process detected: venturo_daemon running with elevated privileges",
    "Checking patch levels...",
    "Critical security patches missing on server (Last update: 2019)",
    "Analyzing system uptime...",
    "System has been online for 180 days without reboot",
    "Attempting to gather employee info...",
    "Employee email database found - 12,573 entries",
    "Suspicious email flagged: ceo@venturocorp.com linked to phishing campaign",
    "Detected external connections to unknown IP: 205.189.122.45",
    "Network anomaly detected: Outbound traffic spike on port 22 (SSH)",
    "Rogue VPN tunnel found, originating from inside network",
    "Running system fingerprint...",
    "OS identified: Ubuntu 18.04 LTS",
    "Kernel version: 4.15.0-142-generic",
    "Checking for backdoor programs...",
    "Backdoor 'Venturo_rootkit' found - installed 3 years ago",
    "Analyzing database dump...",
    "Financial records database accessed by user 'sysadmin'",
    "Unusual spike in data transfer detected over the last hour",
    "Suspicious file found: /var/www/html/venturocorp/data_dump.csv",
    "Checking for compromised endpoints...",
    "Endpoint 192.168.1.34 flagged - Possible malware infection",
    "Botnet activity detected on multiple IPs",
    "Scanned 500 files - 12 infected",
    "Hidden directory found: /opt/venturocorp/stealth-mode/",
    "Checking for anomalies in system processes...",
    "Suspicious process venturo_watcher active",
    "Possible data exfiltration on port 9999",
    "Intrusion detection system logs found, flagged IP: 198.51.100.12",
    "Exploit attempt detected on user 'root'",
    "Checking system logs for abnormal user activity...",
    "Unusual login from 198.51.100.25",
    "Failed login attempt from IP 203.0.113.45",
    "Root access granted at 02:30 AM - User 'unknown'",
    "Suspicious activity: System reboot scheduled by unknown user",
    "Keylogger activity detected in /usr/local/bin/",
    "Active keylogger found: venturo_logger.bin",
    "Network traffic analysis shows large outbound data transfer",
    "Unexpected encrypted payload in network traffic",
    "Detected shell access from external IP: 172.16.0.50",
    "Analyzing system privileges...",
    "System administrator 'venturo_admin' has escalated privileges",
    "Process 'venturo_ai_core' consuming 95% CPU resources",
    "Possible cryptocurrency mining activity detected on server",
    "Detecting data leaks...",
    "Unauthorized file transfer detected: 1.2GB to 192.0.2.55",
    "Unauthorized sudo attempt detected - User: 'guest'",
    "Potential insider threat identified - User 'jdoe' accessing sensitive files",
    "Searching for unencrypted sensitive files...",
    "Plaintext password file found: /var/venturocorp/passwords.txt",
    "Running system resource scan...",
    "System memory at 89% capacity",
    "Disk usage: 95% full on /dev/sda1",
    "Large swap file detected: /tmp/swap.venturocorp.bin",
    "Remote access tool (RAT) detected: venturo_rat_agent.exe",
    "Analyzing system cron jobs...",
    "Suspicious cron job scheduled: /usr/bin/venturo_corp_task",
    "Possible phishing campaign orchestrated by VenturoCorp detected",
    "Running vulnerability scan...",
    "17 high-severity vulnerabilities found in current network setup",
    "Malicious script detected in /var/www/html/venturocorp/assets/scripts/",
    "Flagging endpoint 192.168.1.50 for follow-up analysis",
    "Scan complete. VenturoCorp security compromised."
];


module.exports = systemScanLogs;